package com.faaya.fernandoaranaandrade.demo.Beans;

public enum SettingsEnum {
    WHITE_SEMAFORO,RED_SEMAFORO,ORANGE_SEMAFORO,YELLOW_SEMAFORO, REAL_SEMAFORO, ACTIVE, ON,OFF, BLANCO, VERDE, DATE_NOTIFICATION,ACTIVE_NOTIFICTION, TIME_SNOOZE;
}
